name: Deploy to Cloudflare Pages

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build project
      run: npm run build
      
    - name: Install Wrangler CLI
      run: npm install -g wrangler
      
    - name: Deploy to Cloudflare Pages
      run: |
        echo "请在终端中点击链接完成 Cloudflare 授权登录"
        wrangler pages deploy dist --project-name=quick-transpose --compatibility-date=2024-01-01